export const GOOGLE_SHEETS_CONFIG = {
  sheetId: import.meta.env.VITE_GOOGLE_SHEETS_ID || '1mCB-kI2hacdZHXyBpRKu2vqYfpCIJjDA9Y7xhPKLWP8',
  filmsSheetName: import.meta.env.VITE_GOOGLE_SHEETS_FILMS_SHEET || 'Filme',
  filmsSheets: {
    documentare: 'Documentare',
    fictiune: 'Ficțiune',
    prezentare: 'Filme de prezentare',
    publicitate: 'Publicitate',
    altele: 'Alte producții video',
    proiecte: 'Proiecte',
    distributie: 'Distribuție',
  } as const,
  timeout: 10000,
  retries: 3,
} as const;

export const GOOGLE_SHEETS_COLUMNS = {
  title: ['Titlu', 'Title', 'Titlu film', 'Titlu Film', 'Nume Film', 'Film'],
  slug: ['Slug', 'URL', 'Link'],
  poster_url: [
    'PosterURL',
    'Poster',
    'Poster URL',
    'Imagine',
    'Imagine Poster',
    'Imagini',
    'Poze',
    'Poză',
    'Image',
    'Images',
    'Gallery',
    'Image URL',
    'C',
    'Link imagine',
    'Poster Link',
  ],
  category: ['Categorie', 'Category', 'Categorie film', 'Tip', 'Categoria'],
  release_year: ['An', 'Year', 'An lansare', 'Anul', 'Anul lansării'],
  duration: ['Durata', 'Duration', 'Durata (min)', 'Minute'],
  genre: ['Gen', 'Genre', 'Gen film'],
  director: ['Regizor', 'Director', 'Regizor film'],
  video_link: ['Link Video', 'Video', 'Trailer', 'YouTube'],
  description: ['descriere', 'Descriere', 'Description'],
} as const;
